version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/core"
      - dependency-name: "@nestia/e2e"
      - dependency-name: "@nestia/sdk"
      - dependency-name: "nestia"
      - dependency-name: "typia"
  - package-ecosystem: 'npm'
    directory: '/packages/api'
    schedule:
      interval: 'daily'
    versioning-strategy: increase